# Generated by Django 4.0.1 on 2022-02-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Brand_Image', models.ImageField(upload_to='media/Brands')),
                ('day_left', models.IntegerField()),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_Image', models.ImageField(upload_to='media/Products')),
                ('Product_price', models.IntegerField()),
                ('Stock', models.IntegerField(max_length=5000)),
                ('Product_Brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
