# Generated by Django 3.2.9 on 2022-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220211_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start Date'),
        ),
    ]
