# Generated by Django 4.0.1 on 2022-02-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_brand_expiry_date_alter_brand_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='new1',
        ),
    ]
