# Generated by Django 4.0.1 on 2022-05-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_brand_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Stock',
        ),
    ]
